# Generated by Django 5.0.2 on 2024-04-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioe',
            name='usuario',
            field=models.CharField(default='valor_predeterminado', max_length=100),
        ),
    ]
